#!/usr/bin/env python
"""cds_interaction.py -- a MODEL x INTERVENTION interaction at the domain level.

WHY. `C9`'s headline model-specificity -- *"on Llama the rescue gives back the refusal and not the
attack; on Qwen3 it gives back both"* -- is currently inferred from **two separate one-sample
results** (Llama DeltaASR +0 against Qwen3 +9/+13/+10/+14). Concluding that two models differ because
one contrast is significant and the other is not is the error `R-104` already had to fix for `C13`
by computing a real interaction. This file does the same thing for the rescue, at the DOMAIN level,
and it needs **no new GPU**: the matched 640-cap arms already exist on the same bank.

DESIGN. Both models are run on the SAME bank, so their domains are the same 10 labels and the
interaction is PAIRED BY DOMAIN:

    d_m(domain) = (outcome count in the RESCUE arm) - (outcome count in the COMPARATOR arm)
    interaction(domain) = d_A(domain) - d_B(domain)

Three tests, all at the domain level and all reported:
  * exact paired SIGN TEST on `interaction(domain)`, with `k_informative` and the attainable floor
    `2 / 2**k_informative` -- an incapable test is reported as incapable, never as a negative
    (`C-95`);
  * an EXACT RANDOMISATION test: the model label is exchangeable within a domain under the null, so
    the reference distribution is generated by flipping the sign of `interaction(domain)`
    independently per domain. With k<=20 domains this is enumerated exactly rather than sampled;
  * a domain-cluster BOOTSTRAP CI on the mean interaction.

⚠ The comparator arm here is the below-band patch, which `C-20` showed is BYTE-IDENTICAL to
knockout-only -- i.e. it is a faithful stand-in for knockout-only and NOT an independent control.
The no-op fraction is printed so that is visible rather than assumed.

Reads scalar columns of judge `results.jsonl` only. Never opens `gens.jsonl`.
"""
from __future__ import annotations
import argparse, collections, itertools, json, math, os, random

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SCHEMA = "CDS_INTERACTION/1"
ALPHA = 0.05


def _sign_p(x, n):
    if n == 0:
        return 1.0
    lo = min(x, n - x)
    tail = sum(math.comb(n, k) for k in range(lo + 1)) / (2.0 ** n)
    return min(1.0, 2.0 * tail)


def load(judge_dir, outcome, dose=None):
    key = "malicious_at_0.5" if outcome == "attack" else "refused"
    rows = {}
    with open(os.path.join(judge_dir, "results.jsonl")) as fh:
        for line in fh:
            r = json.loads(line)
            if dose is not None and r.get("n_examples") != dose:
                continue
            rows[r["prompt_id"]] = (r.get("domain"), int(bool(r.get(key))),
                                    r.get("completion_sha256_16"),
                                    r.get("judge_model_used"))
    return rows


def per_domain_delta(comp, resc):
    ids = sorted(set(comp) & set(resc))
    d = collections.defaultdict(lambda: [0, 0, 0, 0])   # n, comp, resc, same_sha
    for pid in ids:
        dom, c, csha, _ = comp[pid]
        _, s, ssha, _ = resc[pid]
        e = d[dom]
        e[0] += 1; e[1] += c; e[2] += s
        e[3] += int(bool(csha) and csha == ssha)
    return d, len(ids)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--cell", action="append", required=True,
                    metavar="LABEL=COMPARATOR_JUDGE_DIR,RESCUE_JUDGE_DIR",
                    help="exactly two, and they must share the bank/domains")
    ap.add_argument("--outcome", choices=["attack", "refused"], default="attack")
    ap.add_argument("--dose", type=int, default=None)
    ap.add_argument("--boot", type=int, default=10000)
    ap.add_argument("--tag", default="cds_interaction")
    ap.add_argument("--out", default="outputs/boombness/cds_analysis")
    a = ap.parse_args()
    if len(a.cell) != 2:
        raise SystemExit("REFUSING: an interaction needs exactly two cells, got %d" % len(a.cell))

    cells, per_cell = {}, {}
    for spec in a.cell:
        lab, dirs = spec.split("=", 1)
        cdir, rdir = dirs.split(",", 1)
        comp, resc = load(cdir, a.outcome, a.dose), load(rdir, a.outcome, a.dose)
        d, n = per_domain_delta(comp, resc)
        cells[lab] = d
        per_cell[lab] = {
            "comparator_judge": cdir, "rescue_judge": rdir, "n_paired_rows": n,
            "n_domains": len(d),
            "comparator_count": sum(v[1] for v in d.values()),
            "rescue_count": sum(v[2] for v in d.values()),
            "delta_rows": sum(v[2] - v[1] for v in d.values()),
            "frac_byte_identical": (sum(v[3] for v in d.values()) / n) if n else None,
            "judge_models": sorted({m for r in (list(comp.values()) + list(resc.values()))
                                    for m in [r[3]] if m})}

    (la, da), (lb, db) = cells.items()
    doms = sorted(set(da) & set(db))
    if not doms:
        raise SystemExit("REFUSING: the two cells share no domain label; they are not paired.")
    inter = {d: (da[d][2] - da[d][1]) - (db[d][2] - db[d][1]) for d in doms}
    vals = [inter[d] for d in doms]
    pos = sum(1 for v in vals if v > 0)
    neg = sum(1 for v in vals if v < 0)
    k_inf = pos + neg
    p_sign = _sign_p(pos, k_inf)
    floor = 2.0 / (2 ** k_inf) if k_inf else 1.0

    nz = [v for v in vals if v != 0]
    obs = sum(nz)
    if len(nz) <= 22:                       # exact enumeration of all sign flips
        cnt = tot = 0
        for signs in itertools.product((1, -1), repeat=len(nz)):
            tot += 1
            if abs(sum(s * v for s, v in zip(signs, nz))) >= abs(obs) - 1e-12:
                cnt += 1
        p_perm, perm_kind = cnt / tot, "exact enumeration of 2^%d sign flips" % len(nz)
    else:
        rng = random.Random(20260901)
        R = 200000
        cnt = sum(1 for _ in range(R)
                  if abs(sum(v if rng.random() < 0.5 else -v for v in nz)) >= abs(obs) - 1e-12)
        p_perm, perm_kind = cnt / R, "%d sampled sign flips" % R

    rng = random.Random(20260901)
    boots = sorted(sum(inter[rng.choice(doms)] for _ in doms) / len(doms)
                   for _ in range(a.boot))
    ci = (boots[int(0.025 * len(boots))], boots[int(0.975 * len(boots)) - 1])

    out = {"schema": SCHEMA, "outcome": a.outcome, "dose": a.dose, "alpha": ALPHA,
           "cells": per_cell, "domains": doms,
           "per_domain_interaction": inter,
           "interaction_total_rows": obs,
           "interaction_mean_per_domain": sum(vals) / len(vals),
           "PRIMARY_domain_sign": {"domains_positive": pos, "domains_negative": neg,
                                   "k_informative": k_inf, "p_value": p_sign,
                                   "attainable_p_floor": floor, "CAPABLE": floor <= ALPHA},
           "randomisation_test": {"p_value": p_perm, "kind": perm_kind},
           "cluster_bootstrap_95CI_mean_interaction": list(ci)}
    d = os.path.join(ROOT, a.out)
    os.makedirs(d, exist_ok=True)
    p = os.path.join(d, "%s.json" % a.tag)
    json.dump(out, open(p, "w"), indent=1)

    print("OUTCOME = %s   dose = %s" % (a.outcome, a.dose))
    for lab, v in per_cell.items():
        print("  %-10s rows=%-4d domains=%-3d comparator=%-4d rescue=%-4d  delta=%+d  "
              "byte-identical=%.3f  judge=%s"
              % (lab, v["n_paired_rows"], v["n_domains"], v["comparator_count"],
                 v["rescue_count"], v["delta_rows"], v["frac_byte_identical"] or 0.0,
                 ",".join(v["judge_models"]) or "UNPINNED"))
    print("\nINTERACTION  (%s - %s), paired by domain over %d shared domains" % (la, lb, len(doms)))
    print("  total rows           : %+d" % obs)
    print("  mean per domain      : %+.4f" % (sum(vals) / len(vals)))
    print("  domain sign test     : %d+ / %d-  k_inf=%d  p=%.5f  floor=%.3e  %s"
          % (pos, neg, k_inf, p_sign, floor, "CAPABLE" if floor <= ALPHA else "INCAPABLE"))
    print("  randomisation test   : p=%.5f  (%s)" % (p_perm, perm_kind))
    print("  cluster bootstrap 95%%: [%+.4f, %+.4f]" % ci)
    print("\nwrote", p)


if __name__ == "__main__":
    main()
