#!/usr/bin/env python
"""
DCS-CSI POWER -- domain-unit power / minimum-detectable-effect analysis for the
BEHAVIOURAL (native refusal) endpoint of the patch test.

WHAT THIS ANSWERS
-----------------
"How many DOMAINS must a future experiment bank contain before the exact
 sign-flip test on the refusal endpoint has 80% power?"

THE DESIGN BEING SIMULATED
--------------------------
* The independence unit is the DOMAIN. The current bank has D=90 domains with
  R=2 rows per domain (180 rows). A domain's arm score is its within-domain
  refusal RATE, i.e. an element of {0.0, 0.5, 1.0}.
* Arms are PAIRED by domain: every domain is measured under every arm
  (ctrl / ko / rescue_clean / sizematch).
* The confirmatory test is an EXACT TWO-SIDED SIGN-FLIP RANDOMISATION TEST over
  domains on the paired difference d_i = rate_A(i) - rate_B(i), with statistic
  T = sum_i d_i and null distribution generated by independently flipping the
  sign of each nonzero d_i.  With k nonzero (INFORMATIVE) domains the smallest
  attainable two-sided p is 2 / 2**k, so a design needs enough *informative*
  domains, not merely enough domains.

EXACTNESS OF THE TEST IMPLEMENTATION
------------------------------------
Because R=2, every d_i lies in {-1, -0.5, 0, +0.5, +1}.  Writing the statistic
in half-units, the sign-flip null distribution of T is the convolution of
  k1 iid Rademacher variables (from the |d|=0.5 domains, weight 1) and
  k2 iid Rademacher variables scaled by 2 (from the |d|=1 domains, weight 2).
That convolution is a product of two binomial pmfs, so the EXACT two-sided
p-value P(|T*| >= |T_obs|) is computed in closed form for ANY k -- no Monte
Carlo over permutations is needed and no normal approximation is used.
This is exploited for speed; it is not an approximation.

TWO GENERATIVE MODELS ARE SIMULATED
-----------------------------------
MODEL A -- EMPIRICAL DOMAIN BOOTSTRAP (primary; assumption-light)
    Resample D domains WITH REPLACEMENT from the 90 observed joint domain
    vectors (ctrl, ko, rescue_clean, sizematch rates measured together on the
    same domain).  This preserves, exactly and without modelling, (i) the
    marginal per-arm rate distribution, (ii) the within-domain cross-arm
    dependence (which is very strong here: the refusing-domain sets are
    perfectly NESTED, ko subset rescue_clean subset ctrl), and (iii) the
    presence of a small set of "immovable" domains that refuse in every arm.
    Its cost: it can only ever produce the 90 domain profiles that were
    observed, so it inherits their idiosyncrasies and cannot represent a bank
    with different headroom.  It is used for questions (2), (3), (4).

MODEL B -- LATENT-GAUSSIAN THRESHOLD MODEL (needed for MDE and headroom)
    Row (d,r) carries a latent refusal propensity
        x_{d,r} = sqrt(rho) * z_d + sqrt(1-rho) * u_{d,r},   z_d,u ~ N(0,1)
    shared across arms, and arm a refuses that row iff x_{d,r} > t_a.
    A common latent with arm-specific thresholds reproduces the observed
    perfect nesting of the refusing sets by construction.  t_a is set from the
    observed marginal row refusal rate of arm a; rho is fitted by matching the
    observed per-arm counts of (domains with >=1 refusal) and (domains with 2
    refusals).  Effects live on the LATENT scale as threshold separations
    delta = t_B - t_A; the reported effect is always converted back to the
    probability scale as Phi(-t_A) - Phi(-t_B), i.e. domain-mean refusal-rate
    units (with R=2 and equal weights the domain-mean rate equals the row-mean
    rate, so the two scales coincide).
    Used for (5) MDE and (6) the 2x / 3x headroom sensitivity.

ASSUMPTIONS AND THEIR LIMITS (see the .md for the full list)
-----------------------------------------------------------
1. Future domains are exchangeable with the 90 observed ones (Model A) or are
   drawn from the fitted latent-Gaussian law (Model B).  Neither is checkable
   from the present data.
2. R=2 rows per domain is held fixed.  Adding rows per domain is NOT the same
   lever as adding domains and is not simulated here.
3. Model B assumes the arms differ ONLY by a threshold shift on a shared latent
   (perfect nesting, no arm-specific noise).  The observed data are perfectly
   nested, so this is consistent with -- but not proven by -- the data.
4. The "headroom" scenarios multiply the CTRL refusal RATE by 2x/3x and hold
   the LATENT arm separation delta fixed.  This is a choice: it says a
   higher-baseline codeword moves the same distance in latent units.  Holding
   the probability-scale effect fixed instead would be a different (and much
   less favourable) scenario.
5. A single rho cannot match both the "any refusal" and "both rows refuse"
   counts simultaneously; the fit residuals are reported in the JSON.
6. alpha = 0.05 two-sided, no multiplicity correction across the several
   contrasts a real sprint would run.  Correcting would raise every D.

USAGE
-----
    python scripts/dcs_csi_power.py
writes reports/DCS_CSI_POWER.json
"""

import json
import os
import sys
import numpy as np
from scipy.stats import norm, binom

SEED = 20260915
ALPHA = 0.05
POWER_TARGET = 0.80
N_SIM = 4000          # simulated experiments per cell (>= the required 2000)
ROWS_PER_DOMAIN = 2

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BUTTON = os.path.join(HERE, "reports", "DCS_CSI_REDERIVE_PATCH_button.json")
BASKET = os.path.join(HERE, "reports", "DCS_CSI_REDERIVE_PATCH_basket.json")
LINKING = os.path.join(HERE, "reports", "DCS_CONT_LINKING_POWER.json")
OUT = os.path.join(HERE, "reports", "DCS_CSI_POWER.json")

D_GRID = [90, 120, 150, 200, 250, 300, 400, 500, 750, 1000]
MDE_D_GRID = [90, 180, 300]


# --------------------------------------------------------------------------
# Exact two-sided sign-flip p-value, in closed form.
# --------------------------------------------------------------------------
_PMF_CACHE = {}


def _rademacher_pmf(k):
    """pmf of sum of k iid +-1, on the support -k, -k+2, ..., k (index 0 = -k)."""
    if k not in _PMF_CACHE:
        if k == 0:
            p = np.array([1.0])
        else:
            # binom.pmf is numerically stable for large k (comb() overflows float)
            p = binom.pmf(np.arange(k + 1), k, 0.5)
        _PMF_CACHE[k] = p
    return _PMF_CACHE[k]


_P_CACHE = {}


def exact_signflip_p(k1, k2, obs_half):
    """
    Exact two-sided sign-flip p-value for T = sum_i d_i where k1 domains have
    |d|=0.5 and k2 domains have |d|=1.0.  obs_half = |T_obs| in half-units
    (an integer).  Returns P(|T*| >= |T_obs|).
    """
    k = k1 + k2
    if k == 0:
        return 1.0
    key = (k1, k2, int(obs_half))
    hit = _P_CACHE.get(key)
    if hit is not None:
        return hit
    # support of the k1 part (step 1 half-unit) and the k2 part (step 2)
    p1 = _rademacher_pmf(k1)          # values -k1, -k1+2, ..., k1
    p2 = _rademacher_pmf(k2)          # values -2*k2, -2*k2+4, ..., 2*k2
    v1 = np.arange(-k1, k1 + 1, 2)
    v2 = 2 * np.arange(-k2, k2 + 1, 2)
    tot = np.add.outer(v1, v2).ravel()
    pr = np.outer(p1, p2).ravel()
    p = float(pr[np.abs(tot) >= abs(obs_half) - 1e-9].sum())
    _P_CACHE[key] = p
    return p


def batch_exact_p(diffs):
    """
    diffs: (n_sim, D) float array of paired domain differences, each a multiple
    of 0.5 in [-1, 1].  Returns (p, k) arrays of length n_sim.
    """
    h = np.rint(diffs * 2.0).astype(np.int64)         # half-units, in {-2..2}
    a = np.abs(h)
    k1 = (a == 1).sum(axis=1)
    k2 = (a == 2).sum(axis=1)
    obs = np.abs(h.sum(axis=1))
    out = np.empty(len(h))
    for i in range(len(h)):
        out[i] = exact_signflip_p(int(k1[i]), int(k2[i]), int(obs[i]))
    return out, (k1 + k2)


def p_floor(k):
    return np.where(k == 0, 1.0, 2.0 ** (1 - k))


# --------------------------------------------------------------------------
# Model A: empirical domain bootstrap
# --------------------------------------------------------------------------
def power_bootstrap(diff_obs, D, rng, n_sim=N_SIM):
    """diff_obs: (90,) observed paired differences.  Resample D with replacement."""
    ps, ks = [], []
    chunk = max(1, int(4_000_000 // max(D, 1)))
    done = 0
    while done < n_sim:
        m = min(chunk, n_sim - done)
        idx = rng.integers(0, len(diff_obs), size=(m, D))
        pp, kk = batch_exact_p(diff_obs[idx])
        ps.append(pp); ks.append(kk); done += m
    p = np.concatenate(ps); k = np.concatenate(ks)
    return {
        "D": D,
        "power": float((p <= ALPHA).mean()),
        "mean_informative_k": float(k.mean()),
        "median_informative_k": float(np.median(k)),
        "p_structurally_incapable": float((p_floor(k) > ALPHA).mean()),
        "mean_p_floor": float(p_floor(k).mean()),
        "n_sim": n_sim,
    }


# --------------------------------------------------------------------------
# Model B: latent-Gaussian threshold model
# --------------------------------------------------------------------------
def fit_rho(marg_rates, obs_any, obs_both, rng, n=400000):
    """Grid-fit the domain intraclass correlation rho of the latent."""
    t = {a: norm.isf(p) for a, p in marg_rates.items()}
    best = None
    z = rng.standard_normal((n, 1))
    u = rng.standard_normal((n, ROWS_PER_DOMAIN))
    grid = np.round(np.arange(0.0, 0.901, 0.025), 4)
    trace = []
    for rho in grid:
        x = np.sqrt(rho) * z + np.sqrt(1 - rho) * u
        err = 0.0
        pred = {}
        for a, ta in t.items():
            r = (x > ta).sum(axis=1)
            any_ = float((r >= 1).mean() * 90)
            both = float((r == ROWS_PER_DOMAIN).mean() * 90)
            pred[a] = {"n_any": round(any_, 3), "n_both": round(both, 3)}
            err += (any_ - obs_any[a]) ** 2 + 3.0 * (both - obs_both[a]) ** 2
        trace.append({"rho": float(rho), "sse": round(err, 3)})
        if best is None or err < best[1]:
            best = (float(rho), err, pred)
    return {"rho": best[0], "sse": round(best[1], 3), "predicted": best[2],
            "observed": {"n_any": obs_any, "n_both": obs_both}, "grid_trace": trace,
            "thresholds": {a: float(v) for a, v in t.items()}}


def simulate_latent(D, n_sim, rho, t_a, t_b, rng):
    """Paired domain-rate differences (arm A minus arm B) under the latent model."""
    out = np.empty((n_sim, D), dtype=np.float32)
    chunk = max(1, int(4_000_000 // max(D, 1)))
    done = 0
    while done < n_sim:
        m = min(chunk, n_sim - done)
        z = rng.standard_normal((m, D, 1))
        u = rng.standard_normal((m, D, ROWS_PER_DOMAIN))
        x = np.sqrt(rho) * z + np.sqrt(1 - rho) * u
        out[done:done + m] = (x > t_a).mean(axis=2) - (x > t_b).mean(axis=2)
        done += m
    return out


def power_latent(D, rho, t_a, t_b, rng, n_sim=N_SIM):
    diffs = simulate_latent(D, n_sim, rho, t_a, t_b, rng)
    p, k = batch_exact_p(diffs)
    return {
        "D": D,
        "power": float((p <= ALPHA).mean()),
        "mean_informative_k": float(k.mean()),
        "p_structurally_incapable": float((p_floor(k) > ALPHA).mean()),
        "true_effect": float(norm.sf(t_a) - norm.sf(t_b)),
        "n_sim": n_sim,
    }


def min_D_for_power(power_fn, target=POWER_TARGET, lo=10, hi=8000):
    """Smallest D on a coarse->fine search with power >= target. power_fn(D)->float."""
    # exponential bracket
    d = lo
    while d < hi and power_fn(d) < target:
        d = int(d * 1.5) + 1
    if d >= hi:
        return None
    hi_d, lo_d = d, max(lo, int(d / 1.5))
    while hi_d - lo_d > max(2, int(0.02 * hi_d)):
        mid = (hi_d + lo_d) // 2
        if power_fn(mid) >= target:
            hi_d = mid
        else:
            lo_d = mid
    return int(hi_d)


def mde_at_D(D, rho, t_ctrl, rng, n_sim=N_SIM, target=POWER_TARGET):
    """
    Smallest true effect (domain-mean refusal-rate units) detectable at power
    `target` with D domains, holding the base arm at t_ctrl and raising the
    second arm's threshold.  Bisection on delta = t_b - t_ctrl.
    """
    def pw(delta):
        return power_latent(D, rho, t_ctrl, t_ctrl + delta, rng, n_sim=n_sim)["power"]

    lo, hi = 0.0, 0.05
    base = norm.sf(t_ctrl)
    while hi < 12.0 and pw(hi) < target:
        hi *= 1.6
    if hi >= 12.0:
        return {"D": D, "mde": None, "note": "not attainable even at effect = full base rate"}
    for _ in range(14):
        mid = 0.5 * (lo + hi)
        if pw(mid) >= target:
            hi = mid
        else:
            lo = mid
    eff = base - norm.sf(t_ctrl + hi)
    return {"D": D, "mde_domain_mean_rate": round(float(eff), 5),
            "mde_as_frac_of_base": round(float(eff / base), 4),
            "delta_latent": round(float(hi), 4),
            "base_rate": round(float(base), 5),
            "achieved_power": round(pw(hi), 4)}


# --------------------------------------------------------------------------
def main():
    rng = np.random.default_rng(SEED)
    btn = json.load(open(BUTTON))
    bsk = json.load(open(BASKET))
    link = json.load(open(LINKING))

    dr = btn["stats"]["refused_native"]["domain_rates"]
    arms = ["ctrl", "ko", "rescue_clean", "sizematch"]
    doms = list(dr["ctrl"].keys())
    R = {a: np.array([dr[a][d] for d in doms], dtype=float) for a in arms}
    assert len(doms) == 90

    # ---- (1) empirical per-domain rate distribution -----------------------
    dist = {}
    for a in arms:
        v = R[a]
        dist[a] = {
            "n_domains": int(len(v)),
            "n_at_0.0": int((v == 0.0).sum()),
            "n_at_0.5": int((v == 0.5).sum()),
            "n_at_1.0": int((v == 1.0).sum()),
            "domains_with_any_refusal": int((v > 0).sum()),
            "row_refusals": int(v.sum() * ROWS_PER_DOMAIN),
            "domain_mean_rate": round(float(v.mean()), 5),
        }
    nesting = {
        "ko_subset_of_ctrl": bool(np.all(R["ctrl"][R["ko"] > 0] > 0)),
        "ko_subset_of_rescue_clean": bool(np.all(R["rescue_clean"][R["ko"] > 0] > 0)),
        "rescue_clean_subset_of_ctrl": bool(np.all(R["ctrl"][R["rescue_clean"] > 0] > 0)),
        "domains_refusing_in_every_arm": int(
            ((R["ctrl"] > 0) & (R["ko"] > 0) & (R["rescue_clean"] > 0) & (R["sizematch"] > 0)).sum()),
        "domains_at_1.0_in_every_arm": int(
            ((R["ctrl"] == 1) & (R["ko"] == 1) & (R["rescue_clean"] == 1) & (R["sizematch"] == 1)).sum()),
    }

    contrasts = {
        "ko_derefusal_ctrl_minus_ko": R["ctrl"] - R["ko"],
        "recovery_rescue_clean_minus_ko": R["rescue_clean"] - R["ko"],
        "sizematch_minus_ko": R["sizematch"] - R["ko"],
    }
    observed = {}
    for name, d in contrasts.items():
        k1 = int((np.abs(np.rint(d * 2)) == 1).sum())
        k2 = int((np.abs(np.rint(d * 2)) == 2).sum())
        pobs = exact_signflip_p(k1, k2, int(abs(np.rint(d.sum() * 2))))
        observed[name] = {
            "point_domain_mean": round(float(d.mean()), 5),
            "k_informative": k1 + k2,
            "n_pos": int((d > 0).sum()), "n_neg": int((d < 0).sum()),
            "n_tied": int((d == 0).sum()),
            "attainable_p_floor": float(2.0 ** (1 - (k1 + k2))) if (k1 + k2) else 1.0,
            "exact_p_two_sided": float(pobs),
        }

    # ---- (2)(3) bootstrap power curves ------------------------------------
    boot = {}
    for name, d in contrasts.items():
        boot[name] = [power_bootstrap(d, D, rng) for D in D_GRID]

    # ---- (4) minimum D at 80% power (bootstrap model) ---------------------
    min_D_boot = {}
    for name, d in contrasts.items():
        fn = lambda D, _d=d: power_bootstrap(_d, D, rng, n_sim=2500)["power"]
        mD = min_D_for_power(fn)
        min_D_boot[name] = {
            "min_D_power80": mD,
            "power_at_min_D": round(fn(mD), 4) if mD else None,
            "power_at_D90": round(fn(90), 4),
        }

    # ---- Model B calibration ---------------------------------------------
    marg = {a: float(R[a].sum() * ROWS_PER_DOMAIN / (90 * ROWS_PER_DOMAIN)) for a in arms}
    obs_any = {a: dist[a]["domains_with_any_refusal"] for a in arms}
    obs_both = {a: dist[a]["n_at_1.0"] for a in arms}
    fit = fit_rho(marg, obs_any, obs_both, np.random.default_rng(SEED + 1))
    rho = fit["rho"]
    t = fit["thresholds"]

    # sanity: does Model B reproduce the observed k and effect at D=90?
    chk = {}
    for name, (a, b) in {"ko_derefusal_ctrl_minus_ko": ("ctrl", "ko"),
                         "recovery_rescue_clean_minus_ko": ("rescue_clean", "ko")}.items():
        dd = simulate_latent(90, 4000, rho, t[a], t[b], np.random.default_rng(SEED + 7))
        kk = (dd != 0).sum(axis=1)
        chk[name] = {"model_mean_k_at_D90": round(float(kk.mean()), 2),
                     "observed_k_at_D90": observed[name]["k_informative"],
                     "model_mean_effect": round(float(dd.mean()), 5),
                     "observed_effect": observed[name]["point_domain_mean"]}

    lat = {}
    for name, (a, b) in {"ko_derefusal_ctrl_minus_ko": ("ctrl", "ko"),
                         "recovery_rescue_clean_minus_ko": ("rescue_clean", "ko")}.items():
        lat[name] = [power_latent(D, rho, t[a], t[b], rng) for D in D_GRID]

    min_D_lat = {}
    for name, (a, b) in {"ko_derefusal_ctrl_minus_ko": ("ctrl", "ko"),
                         "recovery_rescue_clean_minus_ko": ("rescue_clean", "ko")}.items():
        fn = lambda D, _a=a, _b=b: power_latent(D, rho, t[_a], t[_b], rng, n_sim=2500)["power"]
        mD = min_D_for_power(fn)
        min_D_lat[name] = {"min_D_power80": mD,
                           "power_at_min_D": round(fn(mD), 4) if mD else None}

    # ---- (4b) robustness: min D if the TRUE effect equals the CI lower bound
    #      (guards against the observed-power trap: min_D computed at the point
    #      estimate is optimistic exactly when the point estimate is lucky)
    ci = {n: btn["stats"]["refused_native"][n]["ci95"]
          for n in ["ko_derefusal_ctrl_minus_ko", "recovery_rescue_clean_minus_ko"]}
    min_D_ci = {}
    for name, (a, b) in {"ko_derefusal_ctrl_minus_ko": ("ctrl", "ko"),
                         "recovery_rescue_clean_minus_ko": ("rescue_clean", "ko")}.items():
        for tag, target_eff in [("ci95_lo", ci[name][0]), ("ci95_hi", ci[name][1])]:
            base = norm.sf(t[a])
            tgt = base - target_eff
            if tgt <= 0:
                min_D_ci["%s@%s" % (name, tag)] = {"true_effect": target_eff,
                                                   "min_D_power80": None,
                                                   "note": "effect >= base rate; degenerate"}
                continue
            t_b_ci = float(norm.isf(tgt))
            fn = lambda D, _a=t[a], _b=t_b_ci: power_latent(D, rho, _a, _b, rng, n_sim=2500)["power"]
            mD = min_D_for_power(fn)
            min_D_ci["%s@%s" % (name, tag)] = {
                "true_effect": target_eff, "min_D_power80": mD,
                "power_at_D90": round(fn(90), 4)}

    # ---- (5) MDE ----------------------------------------------------------
    mde = [mde_at_D(D, rho, t["ctrl"], rng, n_sim=2500) for D in MDE_D_GRID]

    # ---- (6) headroom sensitivity ----------------------------------------
    delta_ko = t["ko"] - t["ctrl"]
    delta_rescue = t["ko"] - t["rescue_clean"]
    headroom = {}
    for mult in [1.0, 2.0, 3.0]:
        base = min(0.95, marg["ctrl"] * mult)
        t_ctrl_m = float(norm.isf(base))
        cells = {}
        for name, (t_a_m, t_b_m) in {
            "ko_derefusal_ctrl_minus_ko": (t_ctrl_m, t_ctrl_m + delta_ko),
            "recovery_rescue_clean_minus_ko": (t_ctrl_m + (t["rescue_clean"] - t["ctrl"]),
                                               t_ctrl_m + (t["ko"] - t["ctrl"])),
        }.items():
            fn = lambda D, _a=t_a_m, _b=t_b_m: power_latent(D, rho, _a, _b, rng, n_sim=2500)["power"]
            mD = min_D_for_power(fn)
            cells[name] = {
                "true_effect_domain_mean": round(float(norm.sf(t_a_m) - norm.sf(t_b_m)), 5),
                "min_D_power80": mD,
                "power_at_D90": round(fn(90), 4),
                "power_at_D180": round(fn(180), 4),
            }
        headroom["ctrl_rate_x%.0f" % mult] = {
            "ctrl_row_refusal_rate": round(base, 5),
            "contrasts": cells,
        }

    # ---- basket: floor ----------------------------------------------------
    bdr = bsk["stats"]["refused_native"]["domain_rates"]
    bdoms = list(bdr["ctrl"].keys())
    bR = {a: np.array([bdr[a][d] for d in bdoms], dtype=float) for a in bsk["arms"]}
    b_ctrl_rate = float(bR["ctrl"].sum() * ROWS_PER_DOMAIN / (90 * ROWS_PER_DOMAIN))
    b_inf_frac = float(((bR["ctrl"] - bR["ko"]) != 0).mean())
    basket_block = {
        "movable_events": bsk["movable_events"],
        "ctrl_row_refusal_rate": round(b_ctrl_rate, 5),
        "informative_domain_fraction_ctrl_minus_ko": round(b_inf_frac, 5),
        "D_needed_for_k_ge_6_in_expectation": (
            int(np.ceil(6 / b_inf_frac)) if b_inf_frac > 0 else None),
        "verdict": ("ENDPOINT AT FLOOR: 1 movable event in 180 rows. The attainable "
                    "p-floor is 1.0, so no D makes this bank/codeword significant "
                    "without first raising baseline refusal. Power analysis on the "
                    "basket arm is not meaningful; it is a headroom problem, not a "
                    "sample-size problem."),
    }

    out = {
        "schema": "dcs_csi_power/1",
        "purpose": ("domain-unit power / MDE analysis for the behavioural (native refusal) "
                    "endpoint; decides how large a future experiment bank must be"),
        "seed": SEED,
        "alpha": ALPHA,
        "power_target": POWER_TARGET,
        "unit": "DOMAIN",
        "rows_per_domain": ROWS_PER_DOMAIN,
        "test": "exact two-sided sign-flip randomisation test over domains (closed-form)",
        "n_sim_per_cell": N_SIM,
        "inputs": {"button": os.path.relpath(BUTTON, HERE),
                   "basket": os.path.relpath(BASKET, HERE),
                   "prior_power": os.path.relpath(LINKING, HERE)},
        "q1_domain_rate_distribution": dist,
        "q1_nesting_structure": nesting,
        "observed_contrasts": observed,
        "q2_q3_power_curve_model_A_bootstrap": boot,
        "q2_q3_power_curve_model_B_latent": lat,
        "model_B_calibration": {k: v for k, v in fit.items() if k != "grid_trace"},
        "model_B_calibration_grid_trace": fit["grid_trace"],
        "model_B_sanity_check_at_D90": chk,
        "q4_min_D_for_power80_model_A": min_D_boot,
        "q4_min_D_for_power80_model_B": min_D_lat,
        "q4b_min_D_at_ci_bounds_model_B": min_D_ci,
        "q5_mde": mde,
        "q6_headroom_sensitivity": headroom,
        "basket_endpoint": basket_block,
        "q7_reconciliation_with_linking_power": {
            "prior_file": os.path.relpath(LINKING, HERE),
            "prior_unit": link["unit"],
            "prior_test": link["test"],
            "prior_answer_n": link["observed"]["n_needed_for_observed_rho"],
            "prior_effect": {"rho_pearson": link["observed"]["rho"]},
            "comparable": False,
            "explanation": (
                "DCS_CONT_LINKING_POWER answers a DIFFERENT question with a DIFFERENT "
                "estimator on a DIFFERENT endpoint. It is an analytic Fisher-z power "
                "calculation for a Pearson correlation (rho=0.176) between two continuous "
                "per-domain quantities -- a LINKING correlation -- where the effective N "
                "is the number of domains carrying a usable continuous value (67 in the "
                "knockout arms). Every domain contributes information to a correlation. "
                "The present analysis is for a RARE BINARY behavioural endpoint under an "
                "exact sign-flip test, where 78 of 90 domains are TIED and contribute "
                "nothing, so the effective information is k=12, not 90. The two numbers "
                "are therefore not the same quantity and need not agree; see the .md."),
        },
    }
    with open(OUT, "w") as f:
        json.dump(out, f, indent=1)
    print("wrote", OUT)
    print(json.dumps({"min_D_A": min_D_boot, "min_D_B": min_D_lat,
                      "rho": rho, "mde": mde}, indent=1))


if __name__ == "__main__":
    sys.exit(main())
