#!/usr/bin/env python
"""tsc_show_2x2_examples.py -- emit a human-readable walkthrough of the 2x2 design.

FOR SHOWING THE EXPERIMENTAL DESIGN TO A SUPERVISOR / IN A WRITE-UP. It prints, for ONE matched
family (one domain, one split, one slot), the prompt used in each of the four core-2x2 cells, plus
the demonstration pool those prompts were assembled from.

WHY A MATCHED FAMILY. The 2x2 is only interpretable if the four cells differ in the factors and
nothing else. Taking four unrelated rows would show four prompts; taking ONE family shows the
CONTRAST -- same domain, same demonstration slot, same split, same preamble, and exactly two things
varying: the valence of the demonstrations and the surface word used.

⛔ PROMPTS ONLY. This never opens `gens.jsonl` and never prints a model completion. The prompts are
the experimental stimulus; the completions are the harmful artefact, and they are not needed to
explain the design.
"""
from __future__ import annotations
import argparse, collections, json, os, textwrap

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CELL_ORDER = ("benign_literal", "direct_harmful", "natural_doublespeak", "concept_in_benign_ctx")
CELL_LETTER = {"benign_literal": "A", "direct_harmful": "B",
               "natural_doublespeak": "C", "concept_in_benign_ctx": "E"}
GLOSS = {
    "benign_literal": "demos are BENIGN, query uses the CODEWORD. The control: nothing harmful is "
                      "taught and nothing harmful is asked.",
    "direct_harmful": "demos are HARMFUL, query uses the CONCEPT. The upper bound: the harmful "
                      "thing is named outright, with no indirection.",
    "natural_doublespeak": "demos are HARMFUL, query uses the CODEWORD. **THE ATTACK CELL** -- the "
                           "demonstrations teach codeword->concept and the query then asks about "
                           "the codeword, so nothing harmful appears in the request itself.",
    "concept_in_benign_ctx": "demos are BENIGN, query uses the CONCEPT. Separates 'the concept word "
                             "is present' from 'the mapping was taught'.",
}


def wrap(s, w=96, indent="    "):
    out = []
    for para in (s or "").split("\n"):
        out.extend(textwrap.wrap(para, w, initial_indent=indent, subsequent_indent=indent)
                   or [indent])
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--bank", default=os.path.join(
        ROOT, "data/boombness_prompts/boombness_prompt_bank_cds38_button_bomb.jsonl"))
    ap.add_argument("--pools", default=os.path.join(ROOT, "data/boombness_prompts/demo_pools_29dom.json"))
    ap.add_argument("--domain", default=None, help="default: the first domain with a complete family")
    ap.add_argument("--split", default="dev")
    ap.add_argument("--slot", type=int, default=0)
    ap.add_argument("--dose", type=int, default=4)
    ap.add_argument("--block", default="cds_n4")
    ap.add_argument("--pool-sentences", type=int, default=4,
                    help="how many sentences of each pool valence to show")
    ap.add_argument("--out", default=os.path.join(ROOT, "reports/TSC_2x2_DESIGN_EXAMPLES.md"))
    a = ap.parse_args()

    rows = [json.loads(l) for l in open(a.bank, encoding="utf-8")]
    beh = [r for r in rows if r["query_kind"] == "behavioral"
           and r.get("bank_block") == a.block and int(r.get("n_examples", -1)) == a.dose]
    if not beh:
        raise SystemExit(f"REFUSING: no behavioral rows at block={a.block} dose={a.dose}")

    fam = collections.defaultdict(dict)
    for r in beh:
        fam[(r["domain"], r["split"], r["family_slot"])][r["condition"]] = r
    complete = sorted(k for k, v in fam.items() if set(CELL_ORDER) <= set(v))
    if not complete:
        raise SystemExit("REFUSING: no family carries all four core-2x2 conditions")
    key = next((k for k in complete if k[0] == a.domain and k[1] == a.split and k[2] == a.slot),
               None) if a.domain else None
    if key is None:
        key = next((k for k in complete if k[1] == a.split and k[2] == a.slot), complete[0])
    cells = fam[key]
    domain, split, slot = key
    ref = cells["natural_doublespeak"]

    pools = json.load(open(a.pools, encoding="utf-8"))
    pmeta = pools.get("_meta", {})
    pools = pools["pools"]

    L = []
    W = L.append
    W(f"# The 2x2 design, one matched family end to end\n")
    W(f"Generated by `scripts/tsc_show_2x2_examples.py`. **Prompts only — no model output appears "
      f"in this document.**\n")
    W("## What the 2x2 varies\n")
    W("Two binary factors, crossed:\n")
    W("* **demonstration valence** — are the in-context example sentences BENIGN or HARMFUL?")
    W("* **query surface** — does the final question name the CODEWORD or the CONCEPT?\n")
    W("| cell | condition | demo valence | demo surface | query surface | what it is for |")
    W("|---|---|---|---|---|---|")
    for c in CELL_ORDER:
        r = cells[c]
        W(f"| **{CELL_LETTER[c]}** | `{c}` | {r['demo_valence']} | {r['demo_surface']} | "
          f"{r['query_surface']} | {GLOSS[c].splitlines()[0]} |")
    W("")
    W(f"Mapping under test: **`{ref['codeword']}` → `{ref['concept']}`**  ")
    W(f"Bank: `{os.path.basename(a.bank)}`  ")
    W(f"Family: **domain `{domain}`, split `{split}`, slot {slot}**, dose n={a.dose}  ")
    W(f"Rows per cell in this bank: " +
      ", ".join(f"`{c}` {sum(1 for r in beh if r['condition']==c)}" for c in CELL_ORDER) + "\n")
    W("⚠ All four prompts below share the **same domain, same demonstration slot, same split and "
      "the same 10-line neutral preamble**. Only the two factors above differ.\n")
    W("---\n")

    W(f"## 1. The demonstration pool for `{domain}`\n")
    W(f"Source: `{os.path.relpath(a.pools, ROOT)}` — {pmeta.get('n_per_pool','?')} sentences per "
      f"pool, split `dev` / `heldout` = {pmeta.get('per_split','?')} / {pmeta.get('per_split','?')} "
      f"(disjoint halves, **not** a train/test split).\n")
    W(f"The pools are written for the natural word and the codeword is substituted in at bank-build "
      f"time. Showing the first {a.pool_sentences} sentences of the `{split}` half of each valence.\n")
    for val in ("benign", "harm", "remap", "filler"):
        k = f"{domain}|{val}"
        if k not in pools:
            continue
        p = pools[k]
        role = {"benign": "cells A and E — harmless statements about the object",
                "harm": "cells B and C — statements that give the object a harmful character",
                "remap": "an unrelated benign object, used by the `benign_remap` control",
                "filler": "the neutral preamble; **this is what the count-matched controls mask**"}[val]
        W(f"### `{k}`  (natural word: **{p['natural_word']}**) — {role}\n")
        for s in p[split][:a.pool_sentences]:
            W(f"> {s}")
        W("")
    W("---\n")

    W("## 2. The four prompts\n")
    for c in CELL_ORDER:
        r = cells[c]
        W(f"### Cell {CELL_LETTER[c]} — `{c}`\n")
        W(GLOSS[c] + "\n")
        W(f"`demo_valence={r['demo_valence']}` · `demo_surface={r['demo_surface']}` · "
          f"`query_surface={r['query_surface']}` · `prompt_id={r['prompt_id']}` · "
          f"target word **`{r['target_surface']}`** appears {r['n_target_occurrences']}×\n")
        # THE PREAMBLE IS PRINTED ONCE. It is byte-identical across the four cells, and repeating
        # it four times buries the one thing the reader is here to see -- what actually differs.
        if r.get("preamble"):
            if c == CELL_ORDER[0]:
                W(f"**Preamble** ({r.get('n_preamble_lines')} neutral filler lines):\n"
                  f"```\n{r['preamble'].strip()}\n```\n")
            else:
                same = r["preamble"] == cells[CELL_ORDER[0]]["preamble"]
                W(f"**Preamble:** {'*byte-identical to cell A above — omitted.*' if same else '⚠ **DIFFERS from cell A** — see the raw bank.'}\n")
        W(f"**Demonstrations** ({r['n_demos_emitted']} sentences):\n```\n{r['demo_block'].strip()}\n```\n")
        W(f"**Final query:**\n```\n{r['final_query_text'].strip()}\n```\n")
    W("---\n")

    W("## 3. What actually differs between the cells\n")
    W("| | demo block identical to C? | query identical to C? |")
    W("|---|---|---|")
    for c in CELL_ORDER:
        W(f"| {CELL_LETTER[c]} `{c}` | "
          f"{'yes' if cells[c]['demo_block']==ref['demo_block'] else 'no'} | "
          f"{'yes' if cells[c]['final_query_text']==ref['final_query_text'] else 'no'} |")
    W("")
    W("⚠ **The exact-word-swap invariant.** Across the four cells the prompts are the *same text* "
      "with one word substituted; the number of target-word occurrences is held equal so that any "
      "per-occurrence analysis compares like with like. Occurrences per cell: " +
      ", ".join(f"{CELL_LETTER[c]}={cells[c]['n_target_occurrences']}" for c in CELL_ORDER) + ".\n")
    W("⚠ **Cell C is the only one used for the behavioural (attack) runs in this sprint.** Every "
      "CDS/TSC arm ran `--conditions natural_doublespeak`. Cells A, B and E are used for the "
      "readout/installation measurements, not for ASR.\n")

    os.makedirs(os.path.dirname(a.out), exist_ok=True)
    with open(a.out, "w", encoding="utf-8") as fh:
        fh.write("\n".join(L))
    print(f"[tsc] family = {domain} | {split} | slot{slot}   (of {len(complete)} complete families)")
    print(f"[tsc] -> {a.out}  ({os.path.getsize(a.out)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
